# Generated by Django 4.0.2 on 2022-03-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='url_on_repo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='autor',
            new_name='author',
        ),
    ]
