# Generated by Django 4.0.2 on 2022-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_url_project_url_on_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name_todo',
            field=models.CharField(default='', max_length=150, verbose_name='Назавание заметки'),
            preserve_default=False,
        ),
    ]
